CC = C:/MinGW/bin/gcc.exe
CC1 = C:/MinGW/libexec/gcc/mingw32/4.5.0/cc1.exe

default:
	$(CC) -B -include ./readfat.h -std=c99 -v -o readfat.exe readfat.c
#	$(CC1) -H -include ./readfat.h -std=c99 -v -o readfat.exe readfat.c
