/**
 *
 */
package javay.main;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.plaf.ColorUIResource;

import javay.awt.ViewMapPanel;
import javay.distance.city.TGraph;
import javay.util.UCity;
import javay.util.graph.DefaultGraph;
import javay.util.graph.DefaultVertex;
import javay.util.graph.Graph;

/**
 * @author DBJ
 *
 */
public class TestCity {
    private GoThread t = null;

    private Runnable run = null; // 更新组件的线程
    private Component component = null;
    private ViewMapPanel panel = null;

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
		      public void run() {
		TestCity fg = new TestCity();
		      }
		});
	}

	/**
	 *
	 */
	public TestCity() {
		DefaultVertex 北京 = new DefaultVertex(UCity.getCity("北京"));
		DefaultVertex 上海 = new DefaultVertex(UCity.getCity("上海"));
		DefaultVertex 天津 = new DefaultVertex(UCity.getCity("天津"));
		DefaultVertex 重庆 = new DefaultVertex(UCity.getCity("重庆"));
		DefaultVertex 哈尔滨 = new DefaultVertex(UCity.getCity("哈尔滨")); // ★
		DefaultVertex 长春 = new DefaultVertex(UCity.getCity("长春"));
		DefaultVertex 沈阳 = new DefaultVertex(UCity.getCity("沈阳"));
		DefaultVertex 呼和浩特 = new DefaultVertex(UCity.getCity("呼和浩特"));
		DefaultVertex 石家庄 = new DefaultVertex(UCity.getCity("石家庄"));
		DefaultVertex 乌鲁木齐 = new DefaultVertex(UCity.getCity("乌鲁木齐"));
		DefaultVertex 兰州 = new DefaultVertex(UCity.getCity("兰州"));
		DefaultVertex 西宁 = new DefaultVertex(UCity.getCity("西宁"));
		DefaultVertex 西安 = new DefaultVertex(UCity.getCity("西安"));
		DefaultVertex 郑州 = new DefaultVertex(UCity.getCity("郑州"));
		DefaultVertex 济南 = new DefaultVertex(UCity.getCity("济南"));
		DefaultVertex 太原 = new DefaultVertex(UCity.getCity("太原"));
		DefaultVertex 合肥 = new DefaultVertex(UCity.getCity("合肥"));
		DefaultVertex 武汉 = new DefaultVertex(UCity.getCity("武汉"));
		DefaultVertex 长沙 = new DefaultVertex(UCity.getCity("长沙"));
		DefaultVertex 南京 = new DefaultVertex(UCity.getCity("南京"));
		DefaultVertex 成都 = new DefaultVertex(UCity.getCity("成都"));
		DefaultVertex 贵阳 = new DefaultVertex(UCity.getCity("贵阳"));
		DefaultVertex 昆明 = new DefaultVertex(UCity.getCity("昆明"));
		DefaultVertex 南宁 = new DefaultVertex(UCity.getCity("南宁"));
		DefaultVertex 杭州 = new DefaultVertex(UCity.getCity("杭州"));
		DefaultVertex 南昌 = new DefaultVertex(UCity.getCity("南昌"));
		DefaultVertex 广州 = new DefaultVertex(UCity.getCity("广州"));
		DefaultVertex 福州 = new DefaultVertex(UCity.getCity("福州"));
		DefaultVertex 银川 = new DefaultVertex(UCity.getCity("银川"));
		DefaultVertex 青岛 = new DefaultVertex(UCity.getCity("青岛"));
		DefaultVertex 大连 = new DefaultVertex(UCity.getCity("大连"));
		DefaultVertex 深圳 = new DefaultVertex(UCity.getCity("深圳"));
		DefaultVertex 廊坊 = new DefaultVertex(UCity.getCity("廊坊"));
		DefaultVertex 沧州 = new DefaultVertex(UCity.getCity("沧州"));
		DefaultVertex 德州 = new DefaultVertex(UCity.getCity("德州"));
		DefaultVertex 泰安 = new DefaultVertex(UCity.getCity("泰安"));
		DefaultVertex 曲阜 = new DefaultVertex(UCity.getCity("曲阜"));
		DefaultVertex 滕州 = new DefaultVertex(UCity.getCity("滕州"));
		DefaultVertex 枣庄 = new DefaultVertex(UCity.getCity("枣庄"));
		DefaultVertex 徐州 = new DefaultVertex(UCity.getCity("徐州"));
		DefaultVertex 宿州 = new DefaultVertex(UCity.getCity("宿州"));
		DefaultVertex 蚌埠 = new DefaultVertex(UCity.getCity("蚌埠"));
		DefaultVertex 定远 = new DefaultVertex(UCity.getCity("定远"));
		DefaultVertex 滁州 = new DefaultVertex(UCity.getCity("滁州"));
		DefaultVertex 镇江 = new DefaultVertex(UCity.getCity("镇江"));
		DefaultVertex 丹阳 = new DefaultVertex(UCity.getCity("丹阳"));
		DefaultVertex 常州 = new DefaultVertex(UCity.getCity("常州"));
		DefaultVertex 无锡 = new DefaultVertex(UCity.getCity("无锡"));
		DefaultVertex 苏州 = new DefaultVertex(UCity.getCity("苏州"));
		DefaultVertex 昆山 = new DefaultVertex(UCity.getCity("昆山"));
		DefaultVertex 咸宁 = new DefaultVertex(UCity.getCity("咸宁"));
		DefaultVertex 赤壁 = new DefaultVertex(UCity.getCity("赤壁"));
		DefaultVertex 岳阳 = new DefaultVertex(UCity.getCity("岳阳"));
		DefaultVertex 汨罗 = new DefaultVertex(UCity.getCity("汨罗"));
		DefaultVertex 株洲 = new DefaultVertex(UCity.getCity("株洲"));
		DefaultVertex 衡山 = new DefaultVertex(UCity.getCity("衡山"));
		DefaultVertex 衡阳 = new DefaultVertex(UCity.getCity("衡阳"));
		DefaultVertex 耒阳 = new DefaultVertex(UCity.getCity("耒阳"));
		DefaultVertex 郴州 = new DefaultVertex(UCity.getCity("郴州"));
		DefaultVertex 韶关 = new DefaultVertex(UCity.getCity("韶关"));
		DefaultVertex 清远 = new DefaultVertex(UCity.getCity("清远"));
		DefaultVertex 双城 = new DefaultVertex(UCity.getCity("双城"));
		DefaultVertex 扶余 = new DefaultVertex(UCity.getCity("扶余"));
		DefaultVertex 德惠 = new DefaultVertex(UCity.getCity("德惠"));
		DefaultVertex 公主岭 = new DefaultVertex(UCity.getCity("公主岭"));
		DefaultVertex 四平 = new DefaultVertex(UCity.getCity("四平"));
		DefaultVertex 昌图 = new DefaultVertex(UCity.getCity("昌图"));
		DefaultVertex 开原 = new DefaultVertex(UCity.getCity("开原"));
		DefaultVertex 铁岭 = new DefaultVertex(UCity.getCity("铁岭"));
		DefaultVertex 辽阳 = new DefaultVertex(UCity.getCity("辽阳"));
		DefaultVertex 鞍山 = new DefaultVertex(UCity.getCity("鞍山"));
		DefaultVertex 海城 = new DefaultVertex(UCity.getCity("海城"));
		DefaultVertex 营口 = new DefaultVertex(UCity.getCity("营口"));
		DefaultVertex 盖州 = new DefaultVertex(UCity.getCity("盖州"));
		DefaultVertex 鲅鱼圈 = new DefaultVertex(UCity.getCity("鲅鱼圈"));
		DefaultVertex 瓦房店 = new DefaultVertex(UCity.getCity("瓦房店"));
		DefaultVertex 普兰店 = new DefaultVertex(UCity.getCity("普兰店"));
		DefaultVertex 东涌 = new DefaultVertex(UCity.getCity("东涌"));
		DefaultVertex 虎门 = new DefaultVertex(UCity.getCity("虎门"));
		DefaultVertex 龙华 = new DefaultVertex(UCity.getCity("龙华"));
		DefaultVertex 落马洲 = new DefaultVertex(UCity.getCity("落马洲"));
		DefaultVertex 锦上路 = new DefaultVertex(UCity.getCity("锦上路"));
		DefaultVertex 西九龙 = new DefaultVertex(UCity.getCity("西九龙"));
		DefaultVertex 保定 = new DefaultVertex(UCity.getCity("保定"));
		DefaultVertex 高邑 = new DefaultVertex(UCity.getCity("高邑"));
		DefaultVertex 邢台 = new DefaultVertex(UCity.getCity("邢台"));
		DefaultVertex 邯郸 = new DefaultVertex(UCity.getCity("邯郸"));
		DefaultVertex 安阳 = new DefaultVertex(UCity.getCity("安阳"));
		DefaultVertex 鹤壁 = new DefaultVertex(UCity.getCity("鹤壁"));
		DefaultVertex 新乡 = new DefaultVertex(UCity.getCity("新乡"));
		DefaultVertex 许昌 = new DefaultVertex(UCity.getCity("许昌"));
		DefaultVertex 漯河 = new DefaultVertex(UCity.getCity("漯河"));
		DefaultVertex 驻马店 = new DefaultVertex(UCity.getCity("驻马店"));
		DefaultVertex 明港 = new DefaultVertex(UCity.getCity("明港"));
		DefaultVertex 信阳 = new DefaultVertex(UCity.getCity("信阳"));
		DefaultVertex 孝感 = new DefaultVertex(UCity.getCity("孝感"));
		DefaultVertex 荥阳 = new DefaultVertex(UCity.getCity("荥阳"));
		DefaultVertex 巩义 = new DefaultVertex(UCity.getCity("巩义"));
		DefaultVertex 洛阳 = new DefaultVertex(UCity.getCity("洛阳"));
		DefaultVertex 渑池 = new DefaultVertex(UCity.getCity("渑池"));
		DefaultVertex 三门峡 = new DefaultVertex(UCity.getCity("三门峡"));
		DefaultVertex 灵宝 = new DefaultVertex(UCity.getCity("灵宝"));
		DefaultVertex 华山 = new DefaultVertex(UCity.getCity("华山"));
		DefaultVertex 渭南 = new DefaultVertex(UCity.getCity("渭南"));
		DefaultVertex 临潼 = new DefaultVertex(UCity.getCity("临潼"));
		DefaultVertex 咸阳 = new DefaultVertex(UCity.getCity("咸阳"));
		DefaultVertex 杨凌 = new DefaultVertex(UCity.getCity("杨凌"));
		DefaultVertex 五丈原 = new DefaultVertex(UCity.getCity("五丈原"));
		DefaultVertex 宝鸡 = new DefaultVertex(UCity.getCity("宝鸡"));
		DefaultVertex P点 = new DefaultVertex(UCity.getCity("P点"));
		DefaultVertex Q点 = new DefaultVertex(UCity.getCity("Q点"));
		DefaultVertex 古楼子村 = new DefaultVertex(UCity.getCity("古楼子村"));
		DefaultVertex 大蒲石河村 = new DefaultVertex(UCity.getCity("大蒲石河村"));
		DefaultVertex 古楼子乡 = new DefaultVertex(UCity.getCity("古楼子乡"));
		DefaultVertex 丹东 = new DefaultVertex(UCity.getCity("丹东"));
		DefaultVertex 嘉兴 = new DefaultVertex(UCity.getCity("嘉兴"));
		DefaultVertex 诸暨 = new DefaultVertex(UCity.getCity("诸暨"));
		DefaultVertex 义乌 = new DefaultVertex(UCity.getCity("义乌"));
		DefaultVertex 金华 = new DefaultVertex(UCity.getCity("金华"));
		DefaultVertex 衢州 = new DefaultVertex(UCity.getCity("衢州"));
		DefaultVertex 江山 = new DefaultVertex(UCity.getCity("江山"));
		DefaultVertex 玉山 = new DefaultVertex(UCity.getCity("玉山"));
		DefaultVertex 上饶 = new DefaultVertex(UCity.getCity("上饶"));
		DefaultVertex 弋阳 = new DefaultVertex(UCity.getCity("弋阳"));
		DefaultVertex 鹰潭 = new DefaultVertex(UCity.getCity("鹰潭"));
		DefaultVertex 抚州 = new DefaultVertex(UCity.getCity("抚州"));
		DefaultVertex 进贤 = new DefaultVertex(UCity.getCity("进贤"));
		DefaultVertex 高安 = new DefaultVertex(UCity.getCity("高安"));
		DefaultVertex 新余 = new DefaultVertex(UCity.getCity("新余"));
		DefaultVertex 宜春 = new DefaultVertex(UCity.getCity("宜春"));
		DefaultVertex 萍乡 = new DefaultVertex(UCity.getCity("萍乡"));
		DefaultVertex 醴陵 = new DefaultVertex(UCity.getCity("醴陵"));
		DefaultVertex 湘潭 = new DefaultVertex(UCity.getCity("湘潭"));
		DefaultVertex 韶山 = new DefaultVertex(UCity.getCity("韶山"));
		DefaultVertex 娄底 = new DefaultVertex(UCity.getCity("娄底"));
		DefaultVertex 坪上 = new DefaultVertex(UCity.getCity("坪上"));
		DefaultVertex 洋溪 = new DefaultVertex(UCity.getCity("洋溪"));
		DefaultVertex 隆回 = new DefaultVertex(UCity.getCity("隆回"));
		DefaultVertex 北斗溪乡 = new DefaultVertex(UCity.getCity("北斗溪乡"));
		DefaultVertex 怀化 = new DefaultVertex(UCity.getCity("怀化"));
		DefaultVertex 芷江 = new DefaultVertex(UCity.getCity("芷江"));
		DefaultVertex 晃西 = new DefaultVertex(UCity.getCity("晃西"));
		DefaultVertex 玉屏 = new DefaultVertex(UCity.getCity("玉屏"));
		DefaultVertex 三穗 = new DefaultVertex(UCity.getCity("三穗"));
		DefaultVertex 台江 = new DefaultVertex(UCity.getCity("台江"));
		DefaultVertex 凯里 = new DefaultVertex(UCity.getCity("凯里"));
		DefaultVertex 贵定 = new DefaultVertex(UCity.getCity("贵定"));
		DefaultVertex 平坝 = new DefaultVertex(UCity.getCity("平坝"));
		DefaultVertex 安顺 = new DefaultVertex(UCity.getCity("安顺"));
		DefaultVertex 黄果树 = new DefaultVertex(UCity.getCity("黄果树"));
		DefaultVertex 普安 = new DefaultVertex(UCity.getCity("普安"));
		DefaultVertex 盘县 = new DefaultVertex(UCity.getCity("盘县"));
		DefaultVertex 富源 = new DefaultVertex(UCity.getCity("富源"));
		DefaultVertex 曲靖 = new DefaultVertex(UCity.getCity("曲靖"));
		DefaultVertex 小哨 = new DefaultVertex(UCity.getCity("小哨"));
		DefaultVertex 亦庄 = new DefaultVertex(UCity.getCity("亦庄"));
		DefaultVertex 永乐 = new DefaultVertex(UCity.getCity("永乐"));
		DefaultVertex 武清 = new DefaultVertex(UCity.getCity("武清"));
		DefaultVertex 塘沽 = new DefaultVertex(UCity.getCity("塘沽"));
		DefaultVertex 福清 = new DefaultVertex(UCity.getCity("福清"));
		DefaultVertex 莆田 = new DefaultVertex(UCity.getCity("莆田"));
		DefaultVertex 泉州 = new DefaultVertex(UCity.getCity("泉州"));
		DefaultVertex 晋江 = new DefaultVertex(UCity.getCity("晋江"));
		DefaultVertex 厦门 = new DefaultVertex(UCity.getCity("厦门"));
		DefaultVertex 江宁 = new DefaultVertex(UCity.getCity("江宁"));
		DefaultVertex 句容 = new DefaultVertex(UCity.getCity("句容"));
		DefaultVertex 溧水 = new DefaultVertex(UCity.getCity("溧水"));
		DefaultVertex 瓦屋山 = new DefaultVertex(UCity.getCity("瓦屋山"));
		DefaultVertex 溧阳 = new DefaultVertex(UCity.getCity("溧阳"));
		DefaultVertex 宜兴 = new DefaultVertex(UCity.getCity("宜兴"));
		DefaultVertex 长兴 = new DefaultVertex(UCity.getCity("长兴"));
		DefaultVertex 湖州 = new DefaultVertex(UCity.getCity("湖州"));
		DefaultVertex 德清 = new DefaultVertex(UCity.getCity("德清"));
		DefaultVertex 仙西 = new DefaultVertex(UCity.getCity("仙西"));
		DefaultVertex 宝华 = new DefaultVertex(UCity.getCity("宝华"));
		DefaultVertex 丹徒 = new DefaultVertex(UCity.getCity("丹徒"));
		DefaultVertex 戚墅堰 = new DefaultVertex(UCity.getCity("戚墅堰"));
		DefaultVertex 惠山 = new DefaultVertex(UCity.getCity("惠山"));
		DefaultVertex 阳澄湖 = new DefaultVertex(UCity.getCity("阳澄湖"));
		DefaultVertex 陆家浜 = new DefaultVertex(UCity.getCity("陆家浜"));
		DefaultVertex 安亭 = new DefaultVertex(UCity.getCity("安亭"));
		DefaultVertex 南翔 = new DefaultVertex(UCity.getCity("南翔"));
		DefaultVertex 松江 = new DefaultVertex(UCity.getCity("松江"));
		DefaultVertex 金山 = new DefaultVertex(UCity.getCity("金山"));
		DefaultVertex 嘉善 = new DefaultVertex(UCity.getCity("嘉善"));
		DefaultVertex 桐乡 = new DefaultVertex(UCity.getCity("桐乡"));
		DefaultVertex 海宁 = new DefaultVertex(UCity.getCity("海宁"));
		DefaultVertex 余杭 = new DefaultVertex(UCity.getCity("余杭"));
		DefaultVertex 深圳公明 = new DefaultVertex(UCity.getCity("深圳公明"));
		DefaultVertex 光明 = new DefaultVertex(UCity.getCity("光明"));
		DefaultVertex 福田 = new DefaultVertex(UCity.getCity("福田"));
		DefaultVertex 六安 = new DefaultVertex(UCity.getCity("六安"));
		DefaultVertex 汉口 = new DefaultVertex(UCity.getCity("汉口"));
		DefaultVertex 潜江 = new DefaultVertex(UCity.getCity("潜江"));
		DefaultVertex 荆州 = new DefaultVertex(UCity.getCity("荆州"));
		DefaultVertex 枝江 = new DefaultVertex(UCity.getCity("枝江"));
		DefaultVertex 宜昌 = new DefaultVertex(UCity.getCity("宜昌"));
		DefaultVertex 巴东 = new DefaultVertex(UCity.getCity("巴东"));
		DefaultVertex 恩施 = new DefaultVertex(UCity.getCity("恩施"));
		DefaultVertex 万州 = new DefaultVertex(UCity.getCity("万州"));
		DefaultVertex 潼南 = new DefaultVertex(UCity.getCity("潼南"));
		DefaultVertex 遂宁 = new DefaultVertex(UCity.getCity("遂宁"));
		DefaultVertex 南充 = new DefaultVertex(UCity.getCity("南充"));
		DefaultVertex 淮南 = new DefaultVertex(UCity.getCity("淮南"));
		DefaultVertex 长临河 = new DefaultVertex(UCity.getCity("长临河"));
		DefaultVertex 巢湖 = new DefaultVertex(UCity.getCity("巢湖"));
		DefaultVertex 铜陵 = new DefaultVertex(UCity.getCity("铜陵"));
		DefaultVertex 南陵 = new DefaultVertex(UCity.getCity("南陵"));
		DefaultVertex 泾县 = new DefaultVertex(UCity.getCity("泾县"));
		DefaultVertex 旌德 = new DefaultVertex(UCity.getCity("旌德"));
		DefaultVertex 绩溪 = new DefaultVertex(UCity.getCity("绩溪"));
		DefaultVertex 黄山 = new DefaultVertex(UCity.getCity("黄山"));
		DefaultVertex 婺源 = new DefaultVertex(UCity.getCity("婺源"));
		DefaultVertex 德兴 = new DefaultVertex(UCity.getCity("德兴"));
		DefaultVertex 五府山 = new DefaultVertex(UCity.getCity("五府山"));
		DefaultVertex 武夷山 = new DefaultVertex(UCity.getCity("武夷山"));
		DefaultVertex 建阳 = new DefaultVertex(UCity.getCity("建阳"));
		DefaultVertex 建瓯 = new DefaultVertex(UCity.getCity("建瓯"));
		DefaultVertex 南平 = new DefaultVertex(UCity.getCity("南平"));
		DefaultVertex 古田 = new DefaultVertex(UCity.getCity("古田"));
		DefaultVertex 闽清 = new DefaultVertex(UCity.getCity("闽清"));
		DefaultVertex 简阳 = new DefaultVertex(UCity.getCity("简阳"));
		DefaultVertex 资阳 = new DefaultVertex(UCity.getCity("资阳"));
		DefaultVertex 资中 = new DefaultVertex(UCity.getCity("资中"));
		DefaultVertex 内江 = new DefaultVertex(UCity.getCity("内江"));
		DefaultVertex 隆昌 = new DefaultVertex(UCity.getCity("隆昌"));
		DefaultVertex 荣昌 = new DefaultVertex(UCity.getCity("荣昌"));
		DefaultVertex 大足 = new DefaultVertex(UCity.getCity("大足"));
		DefaultVertex 永川 = new DefaultVertex(UCity.getCity("永川"));
		DefaultVertex 建始 = new DefaultVertex(UCity.getCity("建始"));
		DefaultVertex 璧山 = new DefaultVertex(UCity.getCity("璧山"));
		DefaultVertex 沙坪坝 = new DefaultVertex(UCity.getCity("沙坪坝"));
		DefaultVertex 星火 = new DefaultVertex(UCity.getCity("星火"));
		DefaultVertex 顺义 = new DefaultVertex(UCity.getCity("顺义"));
		DefaultVertex 怀柔 = new DefaultVertex(UCity.getCity("怀柔"));
		DefaultVertex 密云 = new DefaultVertex(UCity.getCity("密云"));
		DefaultVertex 兴隆 = new DefaultVertex(UCity.getCity("兴隆"));
		DefaultVertex 承德 = new DefaultVertex(UCity.getCity("承德"));
		DefaultVertex 平泉 = new DefaultVertex(UCity.getCity("平泉"));
		DefaultVertex 牛河梁 = new DefaultVertex(UCity.getCity("牛河梁"));
		DefaultVertex 喀左 = new DefaultVertex(UCity.getCity("喀左"));
		DefaultVertex 朝阳 = new DefaultVertex(UCity.getCity("朝阳"));
		DefaultVertex 北票 = new DefaultVertex(UCity.getCity("北票"));
		DefaultVertex 阜新 = new DefaultVertex(UCity.getCity("阜新"));
		DefaultVertex 黑山 = new DefaultVertex(UCity.getCity("黑山"));
		DefaultVertex 新民 = new DefaultVertex(UCity.getCity("新民"));
		DefaultVertex 开封 = new DefaultVertex(UCity.getCity("开封"));
		DefaultVertex 兰考 = new DefaultVertex(UCity.getCity("兰考"));
		DefaultVertex 商丘 = new DefaultVertex(UCity.getCity("商丘"));
		DefaultVertex 民权 = new DefaultVertex(UCity.getCity("民权"));
		DefaultVertex 砀山 = new DefaultVertex(UCity.getCity("砀山"));
		DefaultVertex 永城 = new DefaultVertex(UCity.getCity("永城"));
		DefaultVertex 萧县 = new DefaultVertex(UCity.getCity("萧县"));
		DefaultVertex 门源 = new DefaultVertex(UCity.getCity("门源"));
		DefaultVertex 民乐 = new DefaultVertex(UCity.getCity("民乐"));
		DefaultVertex 张掖 = new DefaultVertex(UCity.getCity("张掖"));
		DefaultVertex 临泽 = new DefaultVertex(UCity.getCity("临泽"));
		DefaultVertex 酒泉 = new DefaultVertex(UCity.getCity("酒泉"));
		DefaultVertex 嘉峪关 = new DefaultVertex(UCity.getCity("嘉峪关"));
		DefaultVertex 玉门 = new DefaultVertex(UCity.getCity("玉门"));
		DefaultVertex 柳园 = new DefaultVertex(UCity.getCity("柳园"));
		DefaultVertex 哈密 = new DefaultVertex(UCity.getCity("哈密"));
		DefaultVertex 鄯善 = new DefaultVertex(UCity.getCity("鄯善"));
		DefaultVertex 吐鲁番 = new DefaultVertex(UCity.getCity("吐鲁番"));
//		DefaultVertex 贵定 = new DefaultVertex(UCity.getCity("贵定"));
		DefaultVertex 龙里 = new DefaultVertex(UCity.getCity("龙里"));
		DefaultVertex 都匀 = new DefaultVertex(UCity.getCity("都匀"));
		DefaultVertex 从江 = new DefaultVertex(UCity.getCity("从江"));
		DefaultVertex 榕江 = new DefaultVertex(UCity.getCity("榕江"));
		DefaultVertex 三江 = new DefaultVertex(UCity.getCity("三江"));
		DefaultVertex 桂林 = new DefaultVertex(UCity.getCity("桂林"));
		DefaultVertex 恭城 = new DefaultVertex(UCity.getCity("恭城"));
		DefaultVertex 贺州 = new DefaultVertex(UCity.getCity("贺州"));
		DefaultVertex 怀集 = new DefaultVertex(UCity.getCity("怀集"));
		DefaultVertex 肇庆 = new DefaultVertex(UCity.getCity("肇庆"));
		DefaultVertex 三水 = new DefaultVertex(UCity.getCity("三水"));
		DefaultVertex 大同 = new DefaultVertex(UCity.getCity("大同"));
		DefaultVertex 怀仁 = new DefaultVertex(UCity.getCity("怀仁"));
		DefaultVertex 岱岳 = new DefaultVertex(UCity.getCity("岱岳"));
		DefaultVertex 朔州 = new DefaultVertex(UCity.getCity("朔州"));
		DefaultVertex 宁武 = new DefaultVertex(UCity.getCity("宁武"));
		DefaultVertex 原平 = new DefaultVertex(UCity.getCity("原平"));
		DefaultVertex 忻州 = new DefaultVertex(UCity.getCity("忻州"));
		DefaultVertex 榆次 = new DefaultVertex(UCity.getCity("榆次"));
		DefaultVertex 太谷 = new DefaultVertex(UCity.getCity("太谷"));
		DefaultVertex 平遥 = new DefaultVertex(UCity.getCity("平遥"));
		DefaultVertex 介休 = new DefaultVertex(UCity.getCity("介休"));
		DefaultVertex 临汾 = new DefaultVertex(UCity.getCity("临汾"));
		DefaultVertex 侯马 = new DefaultVertex(UCity.getCity("侯马"));
		DefaultVertex 运城 = new DefaultVertex(UCity.getCity("运城"));
		DefaultVertex 永济 = new DefaultVertex(UCity.getCity("永济"));
//		DefaultVertex 华山 = new DefaultVertex(UCity.getCity("华山"));
//		DefaultVertex 渭南 = new DefaultVertex(UCity.getCity("渭南"));
//		DefaultVertex 成都 = new DefaultVertex(UCity.getCity("成都"));
		DefaultVertex 安靖 = new DefaultVertex(UCity.getCity("安靖"));
		DefaultVertex 金牛 = new DefaultVertex(UCity.getCity("金牛"));
		DefaultVertex 犀浦 = new DefaultVertex(UCity.getCity("犀浦"));
		DefaultVertex 红光 = new DefaultVertex(UCity.getCity("红光"));
		DefaultVertex 郫县东 = new DefaultVertex(UCity.getCity("郫县东"));
		DefaultVertex 郫县 = new DefaultVertex(UCity.getCity("郫县"));
		DefaultVertex 郫县西 = new DefaultVertex(UCity.getCity("郫县西"));
		DefaultVertex 安德 = new DefaultVertex(UCity.getCity("安德"));
		DefaultVertex 崇义 = new DefaultVertex(UCity.getCity("崇义"));
		DefaultVertex 聚源 = new DefaultVertex(UCity.getCity("聚源"));
		DefaultVertex 都江堰 = new DefaultVertex(UCity.getCity("都江堰"));
		DefaultVertex 中兴 = new DefaultVertex(UCity.getCity("中兴"));
		DefaultVertex 青城山 = new DefaultVertex(UCity.getCity("青城山"));
		DefaultVertex 九江 = new DefaultVertex(UCity.getCity("九江"));
		DefaultVertex 庐山 = new DefaultVertex(UCity.getCity("庐山"));
		DefaultVertex 德安 = new DefaultVertex(UCity.getCity("德安"));
		DefaultVertex 共青城 = new DefaultVertex(UCity.getCity("共青城"));
		DefaultVertex 永修 = new DefaultVertex(UCity.getCity("永修"));
		DefaultVertex 乐化 = new DefaultVertex(UCity.getCity("乐化"));
		DefaultVertex 榆中 = new DefaultVertex(UCity.getCity("榆中"));
		DefaultVertex 定西 = new DefaultVertex(UCity.getCity("定西"));
		DefaultVertex 通渭 = new DefaultVertex(UCity.getCity("通渭"));
		DefaultVertex 秦安 = new DefaultVertex(UCity.getCity("秦安"));
		DefaultVertex 天水 = new DefaultVertex(UCity.getCity("天水"));
		DefaultVertex 东岔 = new DefaultVertex(UCity.getCity("东岔"));
//		DefaultVertex 宝鸡 = new DefaultVertex(UCity.getCity("宝鸡"));
		DefaultVertex 章丘 = new DefaultVertex(UCity.getCity("章丘"));
		DefaultVertex 周村 = new DefaultVertex(UCity.getCity("周村"));
		DefaultVertex 淄博 = new DefaultVertex(UCity.getCity("淄博"));
		DefaultVertex 临淄 = new DefaultVertex(UCity.getCity("临淄"));
		DefaultVertex 青州 = new DefaultVertex(UCity.getCity("青州"));
		DefaultVertex 昌乐 = new DefaultVertex(UCity.getCity("昌乐"));
		DefaultVertex 潍坊 = new DefaultVertex(UCity.getCity("潍坊"));
		DefaultVertex 昌邑 = new DefaultVertex(UCity.getCity("昌邑"));
		DefaultVertex 高密 = new DefaultVertex(UCity.getCity("高密"));
		DefaultVertex 胶州 = new DefaultVertex(UCity.getCity("胶州"));
		DefaultVertex 藁城 = new DefaultVertex(UCity.getCity("藁城"));
		DefaultVertex 辛集 = new DefaultVertex(UCity.getCity("辛集"));
		DefaultVertex 衡水 = new DefaultVertex(UCity.getCity("衡水"));
		DefaultVertex 景州 = new DefaultVertex(UCity.getCity("景州"));
//		DefaultVertex 德州 = new DefaultVertex(UCity.getCity("德州"));
		DefaultVertex 平原 = new DefaultVertex(UCity.getCity("平原"));
		DefaultVertex 禹城 = new DefaultVertex(UCity.getCity("禹城"));
		DefaultVertex 齐河 = new DefaultVertex(UCity.getCity("齐河"));
		DefaultVertex 凌井 = new DefaultVertex(UCity.getCity("凌井"));
		DefaultVertex 阳泉 = new DefaultVertex(UCity.getCity("阳泉"));
		DefaultVertex 井陉 = new DefaultVertex(UCity.getCity("井陉"));
//		DefaultVertex 厦门 = new DefaultVertex(UCity.getCity("厦门"));
		DefaultVertex 角美 = new DefaultVertex(UCity.getCity("角美"));
		DefaultVertex 漳州 = new DefaultVertex(UCity.getCity("漳州"));
		DefaultVertex 漳浦 = new DefaultVertex(UCity.getCity("漳浦"));
		DefaultVertex 云霄 = new DefaultVertex(UCity.getCity("云霄"));
		DefaultVertex 诏安 = new DefaultVertex(UCity.getCity("诏安"));
		DefaultVertex 饶平 = new DefaultVertex(UCity.getCity("饶平"));
		DefaultVertex 潮汕 = new DefaultVertex(UCity.getCity("潮汕"));
		DefaultVertex 潮阳 = new DefaultVertex(UCity.getCity("潮阳"));
		DefaultVertex 普宁 = new DefaultVertex(UCity.getCity("普宁"));
		DefaultVertex 葵潭 = new DefaultVertex(UCity.getCity("葵潭"));
		DefaultVertex 陆丰 = new DefaultVertex(UCity.getCity("陆丰"));
		DefaultVertex 汕尾 = new DefaultVertex(UCity.getCity("汕尾"));
		DefaultVertex 鲘门 = new DefaultVertex(UCity.getCity("鲘门"));
		DefaultVertex 惠东 = new DefaultVertex(UCity.getCity("惠东"));
		DefaultVertex 惠州 = new DefaultVertex(UCity.getCity("惠州"));
//		DefaultVertex 深圳 = new DefaultVertex(UCity.getCity("深圳"));
		DefaultVertex 本溪新城 = new DefaultVertex(UCity.getCity("本溪新城"));
		DefaultVertex 本溪 = new DefaultVertex(UCity.getCity("本溪"));
		DefaultVertex 南芬 = new DefaultVertex(UCity.getCity("南芬"));
		DefaultVertex 通远堡 = new DefaultVertex(UCity.getCity("通远堡"));
		DefaultVertex 凤城 = new DefaultVertex(UCity.getCity("凤城"));
		DefaultVertex 五龙背 = new DefaultVertex(UCity.getCity("五龙背"));

		DefaultVertex 绍兴 = new DefaultVertex(UCity.getCity("绍兴"));
		DefaultVertex 上虞 = new DefaultVertex(UCity.getCity("上虞"));
		DefaultVertex 余姚 = new DefaultVertex(UCity.getCity("余姚"));
		DefaultVertex 庄桥 = new DefaultVertex(UCity.getCity("庄桥"));
		DefaultVertex 宁波 = new DefaultVertex(UCity.getCity("宁波"));

		//
		DefaultVertex 拉萨 = new DefaultVertex(UCity.getCity("拉萨")); // ★
		DefaultVertex 台北 = new DefaultVertex(UCity.getCity("台北"));
		DefaultVertex 海口 = new DefaultVertex(UCity.getCity("海口")); // ★
		DefaultVertex 香港 = new DefaultVertex(UCity.getCity("香港"));
		DefaultVertex 澳门 = new DefaultVertex(UCity.getCity("澳门"));

		Graph graph = new DefaultGraph();

		graph.setEdge(P点, 大蒲石河村, 1);
		graph.setEdge(大蒲石河村, 古楼子乡, 1);
		graph.setEdge(大蒲石河村, P点, 1);
		graph.setEdge(古楼子乡, 大蒲石河村, 1);
		graph.setEdge(Q点, 古楼子村, 1);
		graph.setEdge(古楼子村, 古楼子乡, 1);
		graph.setEdge(古楼子村, Q点, 1);
		graph.setEdge(古楼子乡, 古楼子村, 1);
		graph.setEdge(丹东, 古楼子乡, 1);
		graph.setEdge(古楼子乡, 丹东, 1);

		// 哈大高铁
		graph.setEdge(哈尔滨, 双城, 1);
		graph.setEdge(双城, 扶余, 1);
		graph.setEdge(扶余, 德惠, 1);
		graph.setEdge(德惠, 长春, 1);
		graph.setEdge(长春, 公主岭, 1);
		graph.setEdge(公主岭, 四平, 1);
		graph.setEdge(四平, 昌图, 1);
		graph.setEdge(昌图, 开原, 1);
		graph.setEdge(开原, 铁岭, 1);
		graph.setEdge(铁岭, 沈阳, 1);
		graph.setEdge(沈阳, 辽阳, 1);
		graph.setEdge(辽阳, 鞍山, 1);
		graph.setEdge(鞍山, 海城, 1);
		graph.setEdge(海城, 营口, 1);
		graph.setEdge(营口, 盖州, 1);
		graph.setEdge(盖州, 鲅鱼圈, 1);
		graph.setEdge(鲅鱼圈, 瓦房店, 1);
		graph.setEdge(瓦房店, 普兰店, 1);
		graph.setEdge(普兰店, 大连, 1);
		graph.setEdge(双城, 哈尔滨, 1);
		graph.setEdge(扶余, 双城, 1);
		graph.setEdge(德惠, 扶余, 1);
		graph.setEdge(长春, 德惠, 1);
		graph.setEdge(公主岭, 长春, 1);
		graph.setEdge(四平, 公主岭, 1);
		graph.setEdge(昌图, 四平, 1);
		graph.setEdge(开原, 昌图, 1);
		graph.setEdge(铁岭, 开原, 1);
		graph.setEdge(沈阳, 铁岭, 1);
		graph.setEdge(辽阳, 沈阳, 1);
		graph.setEdge(鞍山, 辽阳, 1);
		graph.setEdge(海城, 鞍山, 1);
		graph.setEdge(营口, 海城, 1);
		graph.setEdge(盖州, 营口, 1);
		graph.setEdge(鲅鱼圈, 盖州, 1);
		graph.setEdge(瓦房店, 鲅鱼圈, 1);
		graph.setEdge(普兰店, 瓦房店, 1);
		graph.setEdge(大连, 普兰店, 1);

		// 京津高铁★
		graph.setEdge(北京, 亦庄, 1);
		graph.setEdge(亦庄, 永乐, 1);
		graph.setEdge(永乐, 武清, 1);
		graph.setEdge(武清, 天津, 1);
		graph.setEdge(天津, 塘沽, 1);
		graph.setEdge(亦庄, 北京, 1);
		graph.setEdge(永乐, 亦庄, 1);
		graph.setEdge(武清, 永乐, 1);
		graph.setEdge(天津, 武清, 1);
		graph.setEdge(塘沽, 天津, 1);

		// 福厦高铁★
		graph.setEdge(福州, 福清, 1);
		graph.setEdge(福清, 莆田, 1);
		graph.setEdge(莆田, 泉州, 1);
		graph.setEdge(泉州, 晋江, 1);
		graph.setEdge(晋江, 厦门, 1);
		graph.setEdge(福清, 福州, 1);
		graph.setEdge(莆田, 福清, 1);
		graph.setEdge(泉州, 莆田, 1);
		graph.setEdge(晋江, 泉州, 1);
		graph.setEdge(厦门, 晋江, 1);

		// 宁杭高铁★
		graph.setEdge(南京, 江宁, 1);
		graph.setEdge(江宁, 句容, 1);
		graph.setEdge(句容, 溧水, 1);
		graph.setEdge(溧水, 瓦屋山, 1);
		graph.setEdge(瓦屋山, 溧阳, 1);
		graph.setEdge(溧阳, 宜兴, 1);
		graph.setEdge(宜兴, 长兴, 1);
		graph.setEdge(长兴, 湖州, 1);
		graph.setEdge(湖州, 德清, 1);
		graph.setEdge(德清, 杭州, 1);
		graph.setEdge(江宁, 南京, 1);
		graph.setEdge(句容, 江宁, 1);
		graph.setEdge(溧水, 句容, 1);
		graph.setEdge(瓦屋山, 溧水, 1);
		graph.setEdge(溧阳, 瓦屋山, 1);
		graph.setEdge(宜兴, 溧阳, 1);
		graph.setEdge(长兴, 宜兴, 1);
		graph.setEdge(湖州, 长兴, 1);
		graph.setEdge(德清, 湖州, 1);
		graph.setEdge(杭州, 德清, 1);

		// 沪宁高铁★
		graph.setEdge(南京, 仙西, 1);
		graph.setEdge(仙西, 宝华, 1);
		graph.setEdge(宝华, 镇江, 1);
		graph.setEdge(镇江, 丹徒, 1);
		graph.setEdge(丹徒, 丹阳, 1);
		graph.setEdge(丹阳, 常州, 1);
		graph.setEdge(常州, 戚墅堰, 1);
		graph.setEdge(戚墅堰, 惠山, 1);
		graph.setEdge(惠山, 无锡, 1);
		graph.setEdge(无锡, 苏州, 1);
		graph.setEdge(苏州, 阳澄湖, 1);
		graph.setEdge(阳澄湖, 昆山, 1);
		graph.setEdge(昆山, 陆家浜, 1);
		graph.setEdge(陆家浜, 安亭, 1);
		graph.setEdge(安亭, 南翔, 1);
		graph.setEdge(南翔, 上海, 1);
		graph.setEdge(仙西, 南京, 1);
		graph.setEdge(宝华, 仙西, 1);
		graph.setEdge(镇江, 宝华, 1);
		graph.setEdge(丹徒, 镇江, 1);
		graph.setEdge(丹阳, 丹徒, 1);
		graph.setEdge(常州, 丹阳, 1);
		graph.setEdge(戚墅堰, 常州, 1);
		graph.setEdge(惠山, 戚墅堰, 1);
		graph.setEdge(无锡, 惠山, 1);
		graph.setEdge(苏州, 无锡, 1);
		graph.setEdge(阳澄湖, 苏州, 1);
		graph.setEdge(昆山, 阳澄湖, 1);
		graph.setEdge(陆家浜, 昆山, 1);
		graph.setEdge(安亭, 陆家浜, 1);
		graph.setEdge(南翔, 安亭, 1);
		graph.setEdge(上海, 南翔, 1);

		// 沪杭高铁★
		graph.setEdge(上海, 松江, 1);
		graph.setEdge(松江, 金山, 1);
		graph.setEdge(金山, 嘉善, 1);
		graph.setEdge(嘉善, 嘉兴, 1);
		graph.setEdge(嘉兴, 桐乡, 1);
		graph.setEdge(桐乡, 海宁, 1);
		graph.setEdge(海宁, 余杭, 1);
		graph.setEdge(余杭, 杭州, 1);
		graph.setEdge(松江, 上海, 1);
		graph.setEdge(金山, 松江, 1);
		graph.setEdge(嘉善, 金山, 1);
		graph.setEdge(嘉兴, 嘉善, 1);
		graph.setEdge(桐乡, 嘉兴, 1);
		graph.setEdge(海宁, 桐乡, 1);
		graph.setEdge(余杭, 海宁, 1);
		graph.setEdge(杭州, 余杭, 1);

		// 杭甬客运专线
		graph.setEdge(杭州, 绍兴, 1);
		graph.setEdge(绍兴, 上虞, 1);
		graph.setEdge(上虞, 余姚, 1);
		graph.setEdge(余姚, 庄桥, 1);
		graph.setEdge(庄桥, 宁波, 1);
		graph.setEdge(绍兴, 杭州, 1);
		graph.setEdge(上虞, 绍兴, 1);
		graph.setEdge(余姚, 上虞, 1);
		graph.setEdge(庄桥, 余姚, 1);
		graph.setEdge(宁波, 庄桥, 1);


		// 广深港高铁★
		graph.setEdge(广州, 东涌, 1);
		graph.setEdge(东涌, 虎门, 1);
		graph.setEdge(虎门, 深圳公明, 1);
		graph.setEdge(深圳公明, 龙华, 1);
		graph.setEdge(龙华, 落马洲, 1);
		graph.setEdge(落马洲, 锦上路, 1);
		graph.setEdge(锦上路, 西九龙, 1);
		graph.setEdge(东涌, 广州, 1);
		graph.setEdge(虎门, 东涌, 1);
		graph.setEdge(深圳公明, 虎门, 1);
		graph.setEdge(龙华, 深圳公明, 1);
		graph.setEdge(落马洲, 龙华, 1);
		graph.setEdge(锦上路, 落马洲, 1);
		graph.setEdge(西九龙, 锦上路, 1);

		// 广深高铁★
		graph.setEdge(广州, 东涌, 1);
		graph.setEdge(东涌, 虎门, 1);
		graph.setEdge(虎门, 光明, 1);
		graph.setEdge(光明, 深圳, 1);
		graph.setEdge(深圳, 福田, 1);
		graph.setEdge(东涌, 广州, 1);
		graph.setEdge(虎门, 东涌, 1);
		graph.setEdge(光明, 虎门, 1);
		graph.setEdge(深圳, 光明, 1);
		graph.setEdge(福田, 深圳, 1);

////////		graph.setEdge(沈阳, 北京, 1);
////////		graph.setEdge(北京, 沈阳, 1);
////////		graph.setEdge(沈阳, 天津, 1);
//////		graph.setEdge(呼和浩特, 北京, 1);
//////		graph.setEdge(北京, 呼和浩特, 1);
//////		graph.setEdge(济南, 青岛, 1);
//////		graph.setEdge(青岛, 济南, 1);
//////		graph.setEdge(石家庄, 太原, 1);
//////		graph.setEdge(太原, 石家庄, 1);
//////		graph.setEdge(太原, 西安, 1);
//////		graph.setEdge(西安, 太原, 1);
//////		graph.setEdge(西安, 兰州, 1);
//////		graph.setEdge(兰州, 西安, 1);
//////		graph.setEdge(兰州, 西宁, 1);
//////		graph.setEdge(西宁, 兰州, 1);
////////		graph.setEdge(西宁, 乌鲁木齐, 1);
////////		graph.setEdge(乌鲁木齐, 西宁, 1);
//////		graph.setEdge(兰州, 成都, 1);
//////		graph.setEdge(成都, 兰州, 1);
//////		graph.setEdge(成都, 重庆, 1);
//////		graph.setEdge(重庆, 成都, 1);
//////		graph.setEdge(成都, 贵阳, 1);
//////		graph.setEdge(贵阳, 成都, 1);
//////		graph.setEdge(成都, 昆明, 1);
//////		graph.setEdge(昆明, 成都, 1);
//////		graph.setEdge(贵阳, 昆明, 1);
//////		graph.setEdge(昆明, 贵阳, 1);
//////		graph.setEdge(昆明, 南宁, 1);
//////		graph.setEdge(南宁, 昆明, 1);
//////		graph.setEdge(南宁, 广州, 1);
//////		graph.setEdge(广州, 南宁, 1);
//////		graph.setEdge(贵阳, 广州, 1);
//////		graph.setEdge(广州, 贵阳, 1);
//////		graph.setEdge(长沙, 南昌, 1);
//////		graph.setEdge(南昌, 长沙, 1);
//////		graph.setEdge(南昌, 杭州, 1);
//////		graph.setEdge(杭州, 南昌, 1);
//////		graph.setEdge(杭州, 上海, 1);
//////		graph.setEdge(上海, 杭州, 1);
//////		graph.setEdge(杭州, 福州, 1);
//////		graph.setEdge(福州, 杭州, 1);
//////		graph.setEdge(福州, 广州, 1);
//////		graph.setEdge(广州, 福州, 1);
//////		graph.setEdge(福州, 合肥, 1);
//////		graph.setEdge(合肥, 福州, 1);
//////		graph.setEdge(武汉, 合肥, 1);
//////		graph.setEdge(合肥, 武汉, 1);
//////		graph.setEdge(武汉, 重庆, 1);
//////		graph.setEdge(重庆, 武汉, 1);
//////		graph.setEdge(合肥, 南京, 1);
//////		graph.setEdge(南京, 合肥, 1);
//////		graph.setEdge(银川, 兰州, 1);
//////		graph.setEdge(兰州, 银川, 1);
//////		graph.setEdge(银川, 西安, 1);
//////		graph.setEdge(西安, 银川, 1);
//////		graph.setEdge(济南, 合肥, 1);
//////		graph.setEdge(合肥, 济南, 1);
//////		graph.setEdge(西安, 成都, 1);
//////		graph.setEdge(成都, 西安, 1);
//////		graph.setEdge(西安, 重庆, 1);
//////		graph.setEdge(重庆, 西安, 1);
//////		graph.setEdge(西安, 武汉, 1);
//////		graph.setEdge(武汉, 西安, 1);
//////		graph.setEdge(重庆, 长沙, 1);
//////		graph.setEdge(长沙, 重庆, 1);
//////		graph.setEdge(贵阳, 长沙, 1);
//////		graph.setEdge(长沙, 贵阳, 1);
//////		graph.setEdge(西安, 郑州, 1);
//////		graph.setEdge(郑州, 西安, 1);
//////		graph.setEdge(济南, 郑州, 1);
//////		graph.setEdge(郑州, 济南, 1);
//////		graph.setEdge(广州, 深圳, 1);
//////		graph.setEdge(深圳, 广州, 1);

		// 京沪高铁★
		graph.setEdge(北京, 廊坊, 1);
		graph.setEdge(廊坊, 天津, 1);
		graph.setEdge(天津, 沧州, 1);
		graph.setEdge(沧州, 德州, 1);
		graph.setEdge(德州, 济南, 1);
		graph.setEdge(济南, 泰安, 1);
		graph.setEdge(泰安, 曲阜, 1);
		graph.setEdge(曲阜, 滕州, 1);
		graph.setEdge(滕州, 枣庄, 1);
		graph.setEdge(枣庄, 徐州, 1);
		graph.setEdge(徐州, 宿州, 1);
		graph.setEdge(宿州, 蚌埠, 1);
		graph.setEdge(蚌埠, 定远, 1);
		graph.setEdge(定远, 滁州, 1);
		graph.setEdge(滁州, 南京, 1);
		graph.setEdge(南京, 镇江, 1);
		graph.setEdge(镇江, 丹阳, 1);
		graph.setEdge(丹阳, 常州, 1);
		graph.setEdge(常州, 无锡, 1);
		graph.setEdge(无锡, 苏州, 1);
		graph.setEdge(苏州, 昆山, 1);
		graph.setEdge(昆山, 上海, 1);
		graph.setEdge(廊坊, 北京, 1);
		graph.setEdge(天津, 廊坊, 1);
		graph.setEdge(沧州, 天津, 1);
		graph.setEdge(德州, 沧州, 1);
		graph.setEdge(济南, 德州, 1);
		graph.setEdge(泰安, 济南, 1);
		graph.setEdge(曲阜, 泰安, 1);
		graph.setEdge(滕州, 曲阜, 1);
		graph.setEdge(枣庄, 滕州, 1);
		graph.setEdge(徐州, 枣庄, 1);
		graph.setEdge(宿州, 徐州, 1);
		graph.setEdge(蚌埠, 宿州, 1);
		graph.setEdge(定远, 蚌埠, 1);
		graph.setEdge(滁州, 定远, 1);
		graph.setEdge(南京, 滁州, 1);
		graph.setEdge(镇江, 南京, 1);
		graph.setEdge(丹阳, 镇江, 1);
		graph.setEdge(常州, 丹阳, 1);
		graph.setEdge(无锡, 常州, 1);
		graph.setEdge(苏州, 无锡, 1);
		graph.setEdge(昆山, 苏州, 1);
		graph.setEdge(上海, 昆山, 1);
		// 汉广★
		graph.setEdge(武汉, 咸宁, 1);
		graph.setEdge(咸宁, 赤壁, 1);
		graph.setEdge(赤壁, 岳阳, 1);
		graph.setEdge(岳阳, 汨罗, 1);
		graph.setEdge(汨罗, 长沙, 1);
		graph.setEdge(长沙, 株洲, 1);
		graph.setEdge(株洲, 衡山, 1);
		graph.setEdge(衡山, 衡阳, 1);
		graph.setEdge(衡阳, 耒阳, 1);
		graph.setEdge(耒阳, 郴州, 1);
		graph.setEdge(郴州, 韶关, 1);
		graph.setEdge(韶关, 清远, 1);
		graph.setEdge(清远, 广州, 1);
		graph.setEdge(咸宁, 武汉, 1);
		graph.setEdge(赤壁, 咸宁, 1);
		graph.setEdge(岳阳, 赤壁, 1);
		graph.setEdge(汨罗, 岳阳, 1);
		graph.setEdge(长沙, 汨罗, 1);
		graph.setEdge(株洲, 长沙, 1);
		graph.setEdge(衡山, 株洲, 1);
		graph.setEdge(衡阳, 衡山, 1);
		graph.setEdge(耒阳, 衡阳, 1);
		graph.setEdge(郴州, 耒阳, 1);
		graph.setEdge(韶关, 郴州, 1);
		graph.setEdge(清远, 韶关, 1);
		graph.setEdge(广州, 清远, 1);

		graph.setEdge(北京, 保定, 1);
		graph.setEdge(保定, 石家庄, 1);
		graph.setEdge(石家庄, 高邑, 1);
		graph.setEdge(高邑, 邢台, 1);
		graph.setEdge(邢台, 邯郸, 1);
		graph.setEdge(邯郸, 安阳, 1);
		graph.setEdge(安阳, 鹤壁, 1);
		graph.setEdge(鹤壁, 新乡, 1);
		graph.setEdge(新乡, 郑州, 1);
		graph.setEdge(郑州, 许昌, 1);
		graph.setEdge(许昌, 漯河, 1);
		graph.setEdge(漯河, 驻马店, 1);
		graph.setEdge(驻马店, 明港, 1);
		graph.setEdge(明港, 信阳, 1);
		graph.setEdge(信阳, 孝感, 1);
		graph.setEdge(孝感, 武汉, 1);
		graph.setEdge(保定, 北京, 1);
		graph.setEdge(石家庄, 保定, 1);
		graph.setEdge(高邑, 石家庄, 1);
		graph.setEdge(邢台, 高邑, 1);
		graph.setEdge(邯郸, 邢台, 1);
		graph.setEdge(安阳, 邯郸, 1);
		graph.setEdge(鹤壁, 安阳, 1);
		graph.setEdge(新乡, 鹤壁, 1);
		graph.setEdge(郑州, 新乡, 1);
		graph.setEdge(许昌, 郑州, 1);
		graph.setEdge(漯河, 许昌, 1);
		graph.setEdge(驻马店, 漯河, 1);
		graph.setEdge(明港, 驻马店, 1);
		graph.setEdge(信阳, 明港, 1);
		graph.setEdge(孝感, 信阳, 1);
		graph.setEdge(武汉, 孝感, 1);
		// 郑西高铁
		graph.setEdge(郑州, 荥阳, 1);
		graph.setEdge(荥阳, 巩义, 1);
		graph.setEdge(巩义, 洛阳, 1);
		graph.setEdge(洛阳, 渑池, 1);
		graph.setEdge(渑池, 三门峡, 1);
		graph.setEdge(三门峡, 灵宝, 1);
		graph.setEdge(灵宝, 华山, 1);
		graph.setEdge(华山, 渭南, 1);
		graph.setEdge(渭南, 临潼, 1);
		graph.setEdge(临潼, 西安, 1);
		graph.setEdge(西安, 咸阳, 1);
		graph.setEdge(咸阳, 杨凌, 1);
		graph.setEdge(杨凌, 五丈原, 1);
		graph.setEdge(五丈原, 宝鸡, 1);
		graph.setEdge(荥阳, 郑州, 1);
		graph.setEdge(巩义, 荥阳, 1);
		graph.setEdge(洛阳, 巩义, 1);
		graph.setEdge(渑池, 洛阳, 1);
		graph.setEdge(三门峡, 渑池, 1);
		graph.setEdge(灵宝, 三门峡, 1);
		graph.setEdge(华山, 灵宝, 1);
		graph.setEdge(渭南, 华山, 1);
		graph.setEdge(临潼, 渭南, 1);
		graph.setEdge(西安, 临潼, 1);
		graph.setEdge(咸阳, 西安, 1);
		graph.setEdge(杨凌, 咸阳, 1);
		graph.setEdge(五丈原, 杨凌, 1);
		graph.setEdge(宝鸡, 五丈原, 1);
		// 沪昆高铁★
		graph.setEdge(上海, 嘉兴, 1);
		graph.setEdge(嘉兴, 杭州, 1);
		graph.setEdge(杭州, 诸暨, 1);
		graph.setEdge(诸暨, 义乌, 1);
		graph.setEdge(义乌, 金华, 1);
		graph.setEdge(金华, 衢州, 1);
		graph.setEdge(衢州, 江山, 1);
		graph.setEdge(江山, 玉山, 1);
		graph.setEdge(玉山, 上饶, 1);
		graph.setEdge(上饶, 弋阳, 1);
		graph.setEdge(弋阳, 鹰潭, 1);
		graph.setEdge(鹰潭, 抚州, 1);
		graph.setEdge(抚州, 进贤, 1);
		graph.setEdge(进贤, 南昌, 1);
		graph.setEdge(南昌, 高安, 1);
		graph.setEdge(高安, 新余, 1);
		graph.setEdge(新余, 宜春, 1);
		graph.setEdge(宜春, 萍乡, 1);
		graph.setEdge(萍乡, 醴陵, 1);
		graph.setEdge(醴陵, 长沙, 1);
		graph.setEdge(长沙, 湘潭, 1);
		graph.setEdge(湘潭, 韶山, 1);
		graph.setEdge(韶山, 娄底, 1);
		graph.setEdge(娄底, 坪上, 1);
		graph.setEdge(坪上, 洋溪, 1);
		graph.setEdge(洋溪, 隆回, 1);
		graph.setEdge(隆回, 北斗溪乡, 1);
		graph.setEdge(北斗溪乡, 怀化, 1);
		graph.setEdge(怀化, 芷江, 1);
		graph.setEdge(芷江, 晃西, 1);
		graph.setEdge(晃西, 玉屏, 1);
		graph.setEdge(玉屏, 三穗, 1);
		graph.setEdge(三穗, 台江, 1);
		graph.setEdge(台江, 凯里, 1);
		graph.setEdge(凯里, 贵定, 1);
		graph.setEdge(贵定, 贵阳, 1);
		graph.setEdge(贵阳, 平坝, 1);
		graph.setEdge(平坝, 安顺, 1);
		graph.setEdge(安顺, 黄果树, 1);
		graph.setEdge(黄果树, 普安, 1);
		graph.setEdge(普安, 盘县, 1);
		graph.setEdge(盘县, 富源, 1);
		graph.setEdge(富源, 曲靖, 1);
		graph.setEdge(曲靖, 小哨, 1);
		graph.setEdge(小哨, 昆明, 1);
		graph.setEdge(嘉兴, 上海, 1);
		graph.setEdge(杭州, 嘉兴, 1);
		graph.setEdge(诸暨, 杭州, 1);
		graph.setEdge(义乌, 诸暨, 1);
		graph.setEdge(金华, 义乌, 1);
		graph.setEdge(衢州, 金华, 1);
		graph.setEdge(江山, 衢州, 1);
		graph.setEdge(玉山, 江山, 1);
		graph.setEdge(上饶, 玉山, 1);
		graph.setEdge(弋阳, 上饶, 1);
		graph.setEdge(鹰潭, 弋阳, 1);
		graph.setEdge(抚州, 鹰潭, 1);
		graph.setEdge(进贤, 抚州, 1);
		graph.setEdge(南昌, 进贤, 1);
		graph.setEdge(高安, 南昌, 1);
		graph.setEdge(新余, 高安, 1);
		graph.setEdge(宜春, 新余, 1);
		graph.setEdge(萍乡, 宜春, 1);
		graph.setEdge(醴陵, 萍乡, 1);
		graph.setEdge(长沙, 醴陵, 1);
		graph.setEdge(湘潭, 长沙, 1);
		graph.setEdge(韶山, 湘潭, 1);
		graph.setEdge(娄底, 韶山, 1);
		graph.setEdge(坪上, 娄底, 1);
		graph.setEdge(洋溪, 坪上, 1);
		graph.setEdge(隆回, 洋溪, 1);
		graph.setEdge(北斗溪乡, 隆回, 1);
		graph.setEdge(怀化, 北斗溪乡, 1);
		graph.setEdge(芷江, 怀化, 1);
		graph.setEdge(晃西, 芷江, 1);
		graph.setEdge(玉屏, 晃西, 1);
		graph.setEdge(三穗, 玉屏, 1);
		graph.setEdge(台江, 三穗, 1);
		graph.setEdge(凯里, 台江, 1);
		graph.setEdge(贵定, 凯里, 1);
		graph.setEdge(贵阳, 贵定, 1);
		graph.setEdge(平坝, 贵阳, 1);
		graph.setEdge(安顺, 平坝, 1);
		graph.setEdge(黄果树, 安顺, 1);
		graph.setEdge(普安, 黄果树, 1);
		graph.setEdge(盘县, 普安, 1);
		graph.setEdge(富源, 盘县, 1);
		graph.setEdge(曲靖, 富源, 1);
		graph.setEdge(小哨, 曲靖, 1);
		graph.setEdge(昆明, 小哨, 1);
		// 沪汉蓉高铁★
		graph.setEdge(上海, 昆山, 1);
		graph.setEdge(昆山, 苏州, 1);
		graph.setEdge(苏州, 无锡, 1);
		graph.setEdge(无锡, 常州, 1);
		graph.setEdge(常州, 镇江, 1);
		graph.setEdge(镇江, 南京, 1);
		graph.setEdge(南京, 合肥, 1);
		graph.setEdge(合肥, 六安, 1);
		graph.setEdge(六安, 汉口, 1);
		graph.setEdge(汉口, 潜江, 1);
		graph.setEdge(潜江, 荆州, 1);
		graph.setEdge(荆州, 枝江, 1);
		graph.setEdge(枝江, 宜昌, 1);
		graph.setEdge(宜昌, 巴东, 1);
		graph.setEdge(巴东, 恩施, 1);
		graph.setEdge(恩施, 万州, 1);
		graph.setEdge(万州, 重庆, 1);
		graph.setEdge(重庆, 潼南, 1);
		graph.setEdge(潼南, 遂宁, 1);
		graph.setEdge(遂宁, 南充, 1);
		graph.setEdge(南充, 成都, 1);
		graph.setEdge(昆山, 上海, 1);
		graph.setEdge(苏州, 昆山, 1);
		graph.setEdge(无锡, 苏州, 1);
		graph.setEdge(常州, 无锡, 1);
		graph.setEdge(镇江, 常州, 1);
		graph.setEdge(南京, 镇江, 1);
		graph.setEdge(合肥, 南京, 1);
		graph.setEdge(六安, 合肥, 1);
		graph.setEdge(汉口, 六安, 1);
		graph.setEdge(潜江, 汉口, 1);
		graph.setEdge(荆州, 潜江, 1);
		graph.setEdge(枝江, 荆州, 1);
		graph.setEdge(宜昌, 枝江, 1);
		graph.setEdge(巴东, 宜昌, 1);
		graph.setEdge(恩施, 巴东, 1);
		graph.setEdge(万州, 恩施, 1);
		graph.setEdge(重庆, 万州, 1);
		graph.setEdge(潼南, 重庆, 1);
		graph.setEdge(遂宁, 潼南, 1);
		graph.setEdge(南充, 遂宁, 1);
		graph.setEdge(成都, 南充, 1);

		// 京福高铁★
		graph.setEdge(北京, 廊坊, 1);
		graph.setEdge(廊坊, 天津, 1);
		graph.setEdge(天津, 沧州, 1);
		graph.setEdge(沧州, 德州, 1);
		graph.setEdge(德州, 济南, 1);
		graph.setEdge(济南, 泰安, 1);
		graph.setEdge(泰安, 曲阜, 1);
		graph.setEdge(曲阜, 滕州, 1);
		graph.setEdge(滕州, 枣庄, 1);
		graph.setEdge(枣庄, 徐州, 1);
		graph.setEdge(徐州, 宿州, 1);
		graph.setEdge(宿州, 蚌埠, 1);
		graph.setEdge(蚌埠, 淮南, 1);
		graph.setEdge(淮南, 合肥, 1);
		graph.setEdge(合肥, 长临河, 1);
		graph.setEdge(长临河, 巢湖, 1);
		graph.setEdge(巢湖, 铜陵, 1);
		graph.setEdge(铜陵, 南陵, 1);
		graph.setEdge(南陵, 泾县, 1);
		graph.setEdge(泾县, 旌德, 1);
		graph.setEdge(旌德, 绩溪, 1);
		graph.setEdge(绩溪, 黄山, 1);
		graph.setEdge(黄山, 婺源, 1);
		graph.setEdge(婺源, 德兴, 1);
		graph.setEdge(德兴, 上饶, 1);
		graph.setEdge(上饶, 五府山, 1);
		graph.setEdge(五府山, 武夷山, 1);
		graph.setEdge(武夷山, 建阳, 1);
		graph.setEdge(建阳, 建瓯, 1);
		graph.setEdge(建瓯, 南平, 1);
		graph.setEdge(南平, 古田, 1);
		graph.setEdge(古田, 闽清, 1);
		graph.setEdge(闽清, 福州, 1);
		graph.setEdge(廊坊, 北京, 1);
		graph.setEdge(天津, 廊坊, 1);
		graph.setEdge(沧州, 天津, 1);
		graph.setEdge(德州, 沧州, 1);
		graph.setEdge(济南, 德州, 1);
		graph.setEdge(泰安, 济南, 1);
		graph.setEdge(曲阜, 泰安, 1);
		graph.setEdge(滕州, 曲阜, 1);
		graph.setEdge(枣庄, 滕州, 1);
		graph.setEdge(徐州, 枣庄, 1);
		graph.setEdge(宿州, 徐州, 1);
		graph.setEdge(蚌埠, 宿州, 1);
		graph.setEdge(淮南, 蚌埠, 1);
		graph.setEdge(合肥, 淮南, 1);
		graph.setEdge(长临河, 合肥, 1);
		graph.setEdge(巢湖, 长临河, 1);
		graph.setEdge(铜陵, 巢湖, 1);
		graph.setEdge(南陵, 铜陵, 1);
		graph.setEdge(泾县, 南陵, 1);
		graph.setEdge(旌德, 泾县, 1);
		graph.setEdge(绩溪, 旌德, 1);
		graph.setEdge(黄山, 绩溪, 1);
		graph.setEdge(婺源, 黄山, 1);
		graph.setEdge(德兴, 婺源, 1);
		graph.setEdge(上饶, 德兴, 1);
		graph.setEdge(五府山, 上饶, 1);
		graph.setEdge(武夷山, 五府山, 1);
		graph.setEdge(建阳, 武夷山, 1);
		graph.setEdge(建瓯, 建阳, 1);
		graph.setEdge(南平, 建瓯, 1);
		graph.setEdge(古田, 南平, 1);
		graph.setEdge(闽清, 古田, 1);
		graph.setEdge(福州, 闽清, 1);

		// 成渝高铁★
		graph.setEdge(成都, 简阳, 1);
		graph.setEdge(简阳, 资阳, 1);
		graph.setEdge(资阳, 资中, 1);
		graph.setEdge(资中, 内江, 1);
		graph.setEdge(内江, 隆昌, 1);
		graph.setEdge(隆昌, 荣昌, 1);
		graph.setEdge(荣昌, 大足, 1);
		graph.setEdge(大足, 永川, 1);
		graph.setEdge(永川, 璧山, 1);
		graph.setEdge(璧山, 沙坪坝, 1);
		graph.setEdge(沙坪坝, 重庆, 1);
		graph.setEdge(简阳, 成都, 1);
		graph.setEdge(资阳, 简阳, 1);
		graph.setEdge(资中, 资阳, 1);
		graph.setEdge(内江, 资中, 1);
		graph.setEdge(隆昌, 内江, 1);
		graph.setEdge(荣昌, 隆昌, 1);
		graph.setEdge(大足, 荣昌, 1);
		graph.setEdge(永川, 大足, 1);
		graph.setEdge(璧山, 永川, 1);
		graph.setEdge(沙坪坝, 璧山, 1);
		graph.setEdge(重庆, 沙坪坝, 1);

		// 京沈高铁
		graph.setEdge(北京, 星火, 1);
		graph.setEdge(星火, 顺义, 1);
		graph.setEdge(顺义, 怀柔, 1);
		graph.setEdge(怀柔, 密云, 1);
		graph.setEdge(密云, 兴隆, 1);
		graph.setEdge(兴隆, 承德, 1);
		graph.setEdge(承德, 平泉, 1);
		graph.setEdge(平泉, 牛河梁, 1);
		graph.setEdge(牛河梁, 喀左, 1);
		graph.setEdge(喀左, 朝阳, 1);
		graph.setEdge(朝阳, 北票, 1);
		graph.setEdge(北票, 阜新, 1);
		graph.setEdge(阜新, 黑山, 1);
		graph.setEdge(黑山, 新民, 1);
		graph.setEdge(新民, 沈阳, 1);
		graph.setEdge(星火, 北京, 1);
		graph.setEdge(顺义, 星火, 1);
		graph.setEdge(怀柔, 顺义, 1);
		graph.setEdge(密云, 怀柔, 1);
		graph.setEdge(兴隆, 密云, 1);
		graph.setEdge(承德, 兴隆, 1);
		graph.setEdge(平泉, 承德, 1);
		graph.setEdge(牛河梁, 平泉, 1);
		graph.setEdge(喀左, 牛河梁, 1);
		graph.setEdge(朝阳, 喀左, 1);
		graph.setEdge(北票, 朝阳, 1);
		graph.setEdge(阜新, 北票, 1);
		graph.setEdge(黑山, 阜新, 1);
		graph.setEdge(新民, 黑山, 1);
		graph.setEdge(沈阳, 新民, 1);

		// 郑徐高铁
		graph.setEdge(郑州, 开封, 1);
		graph.setEdge(开封, 兰考, 1);
		graph.setEdge(兰考, 商丘, 1);
		graph.setEdge(商丘, 民权, 1);
		graph.setEdge(民权, 砀山, 1);
		graph.setEdge(砀山, 永城, 1);
		graph.setEdge(永城, 萧县, 1);
		graph.setEdge(萧县, 徐州, 1);
		graph.setEdge(开封, 郑州, 1);
		graph.setEdge(兰考, 开封, 1);
		graph.setEdge(商丘, 兰考, 1);
		graph.setEdge(民权, 商丘, 1);
		graph.setEdge(砀山, 民权, 1);
		graph.setEdge(永城, 砀山, 1);
		graph.setEdge(萧县, 永城, 1);
		graph.setEdge(徐州, 萧县, 1);

		// 兰新高铁
		graph.setEdge(兰州, 西宁, 1);
		graph.setEdge(西宁, 门源, 1);
		graph.setEdge(门源, 民乐, 1);
		graph.setEdge(民乐, 张掖, 1);
		graph.setEdge(张掖, 临泽, 1);
		graph.setEdge(临泽, 酒泉, 1);
		graph.setEdge(酒泉, 嘉峪关, 1);
		graph.setEdge(嘉峪关, 玉门, 1);
		graph.setEdge(玉门, 柳园, 1);
		graph.setEdge(柳园, 哈密, 1);
		graph.setEdge(哈密, 鄯善, 1);
		graph.setEdge(鄯善, 吐鲁番, 1);
		graph.setEdge(吐鲁番, 乌鲁木齐, 1);
		graph.setEdge(西宁, 兰州, 1);
		graph.setEdge(门源, 西宁, 1);
		graph.setEdge(民乐, 门源, 1);
		graph.setEdge(张掖, 民乐, 1);
		graph.setEdge(临泽, 张掖, 1);
		graph.setEdge(酒泉, 临泽, 1);
		graph.setEdge(嘉峪关, 酒泉, 1);
		graph.setEdge(玉门, 嘉峪关, 1);
		graph.setEdge(柳园, 玉门, 1);
		graph.setEdge(哈密, 柳园, 1);
		graph.setEdge(鄯善, 哈密, 1);
		graph.setEdge(吐鲁番, 鄯善, 1);
		graph.setEdge(乌鲁木齐, 吐鲁番, 1);

		// 贵广高铁
		graph.setEdge(贵阳, 龙里, 1);
		graph.setEdge(龙里, 贵定, 1);
		graph.setEdge(贵定, 都匀, 1);
		graph.setEdge(都匀, 榕江, 1);
		graph.setEdge(榕江, 从江, 1);
		graph.setEdge(从江, 三江, 1);
		graph.setEdge(三江, 桂林, 1);
		graph.setEdge(桂林, 恭城, 1);
		graph.setEdge(恭城, 贺州, 1);
		graph.setEdge(贺州, 怀集, 1);
		graph.setEdge(怀集, 肇庆, 1);
		graph.setEdge(肇庆, 三水, 1);
		graph.setEdge(三水, 广州, 1);
		graph.setEdge(龙里, 贵阳, 1);
		graph.setEdge(贵定, 龙里, 1);
		graph.setEdge(都匀, 贵定, 1);
		graph.setEdge(榕江, 都匀, 1);
		graph.setEdge(从江, 榕江, 1);
		graph.setEdge(三江, 从江, 1);
		graph.setEdge(桂林, 三江, 1);
		graph.setEdge(恭城, 桂林, 1);
		graph.setEdge(贺州, 恭城, 1);
		graph.setEdge(怀集, 贺州, 1);
		graph.setEdge(肇庆, 怀集, 1);
		graph.setEdge(三水, 肇庆, 1);
		graph.setEdge(广州, 三水, 1);

		// 大西高铁
		graph.setEdge(大同, 怀仁, 1);
		graph.setEdge(怀仁, 岱岳, 1);
		graph.setEdge(岱岳, 朔州, 1);
		graph.setEdge(朔州, 宁武, 1);
		graph.setEdge(宁武, 原平, 1);
		graph.setEdge(原平, 忻州, 1);
		graph.setEdge(忻州, 太原, 1);
		graph.setEdge(太原, 榆次, 1);
		graph.setEdge(榆次, 太谷, 1);
		graph.setEdge(太谷, 平遥, 1);
		graph.setEdge(平遥, 介休, 1);
		graph.setEdge(介休, 临汾, 1);
		graph.setEdge(临汾, 侯马, 1);
		graph.setEdge(侯马, 运城, 1);
		graph.setEdge(运城, 永济, 1);
		graph.setEdge(永济, 华山, 1);
		graph.setEdge(华山, 渭南, 1);
		graph.setEdge(渭南, 西安, 1);
		graph.setEdge(怀仁, 大同, 1);
		graph.setEdge(岱岳, 怀仁, 1);
		graph.setEdge(朔州, 岱岳, 1);
		graph.setEdge(宁武, 朔州, 1);
		graph.setEdge(原平, 宁武, 1);
		graph.setEdge(忻州, 原平, 1);
		graph.setEdge(太原, 忻州, 1);
		graph.setEdge(榆次, 太原, 1);
		graph.setEdge(太谷, 榆次, 1);
		graph.setEdge(平遥, 太谷, 1);
		graph.setEdge(介休, 平遥, 1);
		graph.setEdge(临汾, 介休, 1);
		graph.setEdge(侯马, 临汾, 1);
		graph.setEdge(运城, 侯马, 1);
		graph.setEdge(永济, 运城, 1);
		graph.setEdge(华山, 永济, 1);
		graph.setEdge(渭南, 华山, 1);
		graph.setEdge(西安, 渭南, 1);

		// 成灌快铁
		graph.setEdge(成都, 安靖, 1);
		graph.setEdge(安靖, 金牛, 1);
		graph.setEdge(金牛, 犀浦, 1);
		graph.setEdge(犀浦, 红光, 1);
		graph.setEdge(红光, 郫县东, 1);
		graph.setEdge(郫县东, 郫县, 1);
		graph.setEdge(郫县, 郫县西, 1);
		graph.setEdge(郫县西, 安德, 1);
		graph.setEdge(安德, 崇义, 1);
		graph.setEdge(崇义, 聚源, 1);
		graph.setEdge(聚源, 都江堰, 1);
		graph.setEdge(都江堰, 中兴, 1);
		graph.setEdge(中兴, 青城山, 1);
		graph.setEdge(安靖, 成都, 1);
		graph.setEdge(金牛, 安靖, 1);
		graph.setEdge(犀浦, 金牛, 1);
		graph.setEdge(红光, 犀浦, 1);
		graph.setEdge(郫县东, 红光, 1);
		graph.setEdge(郫县, 郫县东, 1);
		graph.setEdge(郫县西, 郫县, 1);
		graph.setEdge(安德, 郫县西, 1);
		graph.setEdge(崇义, 安德, 1);
		graph.setEdge(聚源, 崇义, 1);
		graph.setEdge(都江堰, 聚源, 1);
		graph.setEdge(中兴, 都江堰, 1);
		graph.setEdge(青城山, 中兴, 1);


		// 昌九高铁
		graph.setEdge(九江, 庐山, 1);
		graph.setEdge(庐山, 德安, 1);
		graph.setEdge(德安, 共青城, 1);
		graph.setEdge(共青城, 永修, 1);
		graph.setEdge(永修, 乐化, 1);
		graph.setEdge(乐化, 南昌, 1);
		graph.setEdge(庐山, 九江, 1);
		graph.setEdge(德安, 庐山, 1);
		graph.setEdge(共青城, 德安, 1);
		graph.setEdge(永修, 共青城, 1);
		graph.setEdge(乐化, 永修, 1);
		graph.setEdge(南昌, 乐化, 1);

		// 宝兰高铁
		graph.setEdge(兰州, 榆中, 1);
		graph.setEdge(榆中, 定西, 1);
		graph.setEdge(定西, 通渭, 1);
		graph.setEdge(通渭, 秦安, 1);
		graph.setEdge(秦安, 天水, 1);
		graph.setEdge(天水, 东岔, 1);
		graph.setEdge(东岔, 宝鸡, 1);
		graph.setEdge(榆中, 兰州, 1);
		graph.setEdge(定西, 榆中, 1);
		graph.setEdge(通渭, 定西, 1);
		graph.setEdge(秦安, 通渭, 1);
		graph.setEdge(天水, 秦安, 1);
		graph.setEdge(东岔, 天水, 1);
		graph.setEdge(宝鸡, 东岔, 1);

		// 胶济客运专线
		graph.setEdge(济南, 章丘, 1);
		graph.setEdge(章丘, 周村, 1);
		graph.setEdge(周村, 淄博, 1);
		graph.setEdge(淄博, 临淄, 1);
		graph.setEdge(临淄, 青州, 1);
		graph.setEdge(青州, 昌乐, 1);
		graph.setEdge(昌乐, 潍坊, 1);
		graph.setEdge(潍坊, 昌邑, 1);
		graph.setEdge(昌邑, 高密, 1);
		graph.setEdge(高密, 胶州, 1);
		graph.setEdge(胶州, 青岛, 1);
		graph.setEdge(章丘, 济南, 1);
		graph.setEdge(周村, 章丘, 1);
		graph.setEdge(淄博, 周村, 1);
		graph.setEdge(临淄, 淄博, 1);
		graph.setEdge(青州, 临淄, 1);
		graph.setEdge(昌乐, 青州, 1);
		graph.setEdge(潍坊, 昌乐, 1);
		graph.setEdge(昌邑, 潍坊, 1);
		graph.setEdge(高密, 昌邑, 1);
		graph.setEdge(胶州, 高密, 1);
		graph.setEdge(青岛, 胶州, 1);


		// 石济客运专线
		graph.setEdge(石家庄, 藁城, 1);
		graph.setEdge(藁城, 辛集, 1);
		graph.setEdge(辛集, 衡水, 1);
		graph.setEdge(衡水, 景州, 1);
		graph.setEdge(景州, 德州, 1);
		graph.setEdge(德州, 平原, 1);
		graph.setEdge(平原, 禹城, 1);
		graph.setEdge(禹城, 齐河, 1);
		graph.setEdge(齐河, 济南, 1);
		graph.setEdge(藁城, 石家庄, 1);
		graph.setEdge(辛集, 藁城, 1);
		graph.setEdge(衡水, 辛集, 1);
		graph.setEdge(景州, 衡水, 1);
		graph.setEdge(德州, 景州, 1);
		graph.setEdge(平原, 德州, 1);
		graph.setEdge(禹城, 平原, 1);
		graph.setEdge(齐河, 禹城, 1);
		graph.setEdge(济南, 齐河, 1);

		// 石太客运专线
		graph.setEdge(太原, 凌井, 1);
		graph.setEdge(凌井, 阳泉, 1);
		graph.setEdge(阳泉, 井陉, 1);
		graph.setEdge(井陉, 石家庄, 1);
		graph.setEdge(凌井, 太原, 1);
		graph.setEdge(阳泉, 凌井, 1);
		graph.setEdge(井陉, 阳泉, 1);
		graph.setEdge(石家庄, 井陉, 1);

		// 厦深铁路
		graph.setEdge(厦门, 角美, 1);
		graph.setEdge(角美, 漳州, 1);
		graph.setEdge(漳州, 漳浦, 1);
		graph.setEdge(漳浦, 云霄, 1);
		graph.setEdge(云霄, 诏安, 1);
		graph.setEdge(诏安, 饶平, 1);
		graph.setEdge(饶平, 潮汕, 1);
		graph.setEdge(潮汕, 潮阳, 1);
		graph.setEdge(潮阳, 普宁, 1);
		graph.setEdge(普宁, 葵潭, 1);
		graph.setEdge(葵潭, 陆丰, 1);
		graph.setEdge(陆丰, 汕尾, 1);
		graph.setEdge(汕尾, 鲘门, 1);
		graph.setEdge(鲘门, 惠东, 1);
		graph.setEdge(惠东, 惠州, 1);
		graph.setEdge(惠州, 深圳, 1);
		graph.setEdge(角美, 厦门, 1);
		graph.setEdge(漳州, 角美, 1);
		graph.setEdge(漳浦, 漳州, 1);
		graph.setEdge(云霄, 漳浦, 1);
		graph.setEdge(诏安, 云霄, 1);
		graph.setEdge(饶平, 诏安, 1);
		graph.setEdge(潮汕, 饶平, 1);
		graph.setEdge(潮阳, 潮汕, 1);
		graph.setEdge(普宁, 潮阳, 1);
		graph.setEdge(葵潭, 普宁, 1);
		graph.setEdge(陆丰, 葵潭, 1);
		graph.setEdge(汕尾, 陆丰, 1);
		graph.setEdge(鲘门, 汕尾, 1);
		graph.setEdge(惠东, 鲘门, 1);
		graph.setEdge(惠州, 惠东, 1);
		graph.setEdge(深圳, 惠州, 1);

		// 沈丹客运专线
		graph.setEdge(沈阳, 本溪新城, 1);
		graph.setEdge(本溪新城, 本溪, 1);
		graph.setEdge(本溪, 南芬, 1);
		graph.setEdge(南芬, 通远堡, 1);
		graph.setEdge(通远堡, 凤城, 1);
		graph.setEdge(凤城, 五龙背, 1);
		graph.setEdge(五龙背, 丹东, 1);
		graph.setEdge(本溪新城, 沈阳, 1);
		graph.setEdge(本溪, 本溪新城, 1);
		graph.setEdge(南芬, 本溪, 1);
		graph.setEdge(通远堡, 南芬, 1);
		graph.setEdge(凤城, 通远堡, 1);
		graph.setEdge(五龙背, 凤城, 1);
		graph.setEdge(丹东, 五龙背, 1);

		System.out.println("Graph is Created.");

//
//        Vertex[] sorted = new Vertex[graph.size()];
//        graph.topologySort(sorted);
////        graph.topologySort_byDFS(sorted);
//        System.out.println("Topology Sort Result==============:");
//        for(int i = 0; i < sorted.length; i ++) {
//        	System.out.println(sorted[i] + ",");
//        }
//        System.out.println();

        JFrame frame = new JFrame();
        // ViewMapPanel panel = new ViewMapPanel(graph);
        panel = new ViewMapPanel(graph);
        JPanel panelBtn = new JPanel();
        JButton dftBtn = new JButton("DFT");
        dftBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.out.println("DFT begin");
				panel.removeAll();

				graph.depthFirstTraversal(new TGraph(panel, ColorUIResource.GREEN));

				System.out.println("DFT end size:" + panel.getComponentCount());

                t = new GoThread();
                t.start();

			}
        });
        JButton bftBtn = new JButton("BFT");
        bftBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.out.println("BFT");
				panel.removeAll();

				graph.breathFirstTraversal(new TGraph(panel, ColorUIResource.BLUE));

                t = new GoThread();
                t.start();

			}
        });
        JButton ksjBtn = new JButton("KSJ");
        ksjBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.out.println("KSJ");
				panel.removeAll();
				graph.kosaraju(new TGraph(panel, ColorUIResource.YELLOW));
                t = new GoThread();
                t.start();
			}
        });
        JButton trjBtn = new JButton("TRJ");
        trjBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.out.println("TRJ");
				panel.removeAll();
				graph.tarjan(new TGraph(panel, ColorUIResource.BLUE));
			}
        });
        JButton gbwBtn = new JButton("GBW");
        gbwBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.out.println("GBW");
				panel.removeAll();
				graph.Gabow(new TGraph(panel, ColorUIResource.BLUE));
			}
        });
        // JButton b = new JButton("按我", new ImageIcon(".\\icons\\hand.jpg"));
        Container contentPane = frame.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(panel, BorderLayout.CENTER);
        contentPane.add(panelBtn, BorderLayout.LINE_END);
        panelBtn.setLayout(new GridLayout(5, 1));
        panelBtn.add(dftBtn);
        panelBtn.add(bftBtn);
        panelBtn.add(ksjBtn);
        panelBtn.add(trjBtn);
        panelBtn.add(gbwBtn);
        frame.setLocation(0, 0);
        frame.setTitle("图测试");
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.pack();
        frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

        run = new Runnable() { //实例化更新组件的线程
            public void run() {
            	component.repaint();
            }
        };

//        InstructionListener il = new InstructionListener(panel);
//        frame.addKeyListener(il);
	}

    class GoThread extends Thread {
        public void run() {
        	for (int i = 0; i < panel.getComponentCount(); i ++) {
        		component = panel.getComponent(i);
        		//do something...
        		go();
        	}
        	panel.repaint();
        }
    }

    private void go() {
        try {
            Thread.sleep(200);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        SwingUtilities.invokeLater(run);//将对象排到事件派发线程的队列中
    }
}
